version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DB_URI=mongodb://mongo:27017/ecommerce
      - JWT_SECRET=dev.JWT.secret.yair@local
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads

volumes:
  mongo-data:
